version: '3.8'
services:
  fe-app:
    image: registry.cn-chengdu.aliyuncs.com/react_2205/meeting-fe:test1
    ports:
      - 80:80
    depends_on:
      - nest-app
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    # ports:
    #   - 3100:3100
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/jincheng/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: 202411
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/jincheng/redis-data:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
